services:
  asks-db:
    image: mysql:9.0.1
    container_name: asks_db
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - asks:/var/lib/mysql

volumes:
  asks: